### ISSUE TITLE
[BUG] - User is not able to change settings if backup power for Wi-Fi is disabled 🤦

### ISSUE THREAD

**Issue by GodHermit** [GodHermit/smart-power-backup#18]
### Description

WTF, I even thought, when programmed this🤦

I see two options for resolving this bug:
1. Creating access point when power backup is disabled.
2. Using access point only.

Both solution looks odd for me.
First one seems good, but GUI may be available under different IPs.
Second seems like more secure and stable, but GUI will available under specific network only

### Reproduction steps

```bash
1. Connect Wi-Fi power backup
2. Log into an account
3. Change settings `isPowerBackupEnabled` to `false`

Actual result: Wi-Fi turns off -> Wi-Fi connection fails -> user cannot change settings back to `true`
Expected result: Wi-Fi turns off -> RPi Pico creates [access point](https://kalumajs.org/docs/api/cyw43#class-picocyw43wifi)
```

**Comment by GodHermit** [comment]
## TODO:

- [x] Implement second option "Using access point only." with [AP Mode](https://kalumajs.org/docs/api/cyw43#pico_cyw43wifiapmodeapinfo-callback)

- [x] Update ENVs:  
  - [x] Change `WIFI_SSID` to `ACCESS_POINT_SSID`
  - [x] Change `WIFI_PASSWORD` to `ACCESS_POINT_PASSWORD`
  - [x] Add `ACCESS_POINT_GATEWAY`. **Default:** `192.168.0.1`

- [x] Update [API-Build workflow](https://github.com/GodHermit/smart-power-backup/blob/main/.github/workflows/API-Build.yml)
  - [x] Set default values for all fields
  - [x] Add trigger on PR open event + pushes after that

**Comment by GodHermit** [comment]
Resolved by #20 PR
